package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"errors"
	"net/http"
	"time"

	"github.com/KeiKom083/Portfolio-Backend/internal/domain/model"
	"github.com/KeiKom083/Portfolio-Backend/internal/interface/graphql/generated"
	"github.com/KeiKom083/Portfolio-Backend/internal/interface/graphql/middleware"
	"github.com/KeiKom083/Portfolio-Backend/internal/usecase"
)

const (
	timeLayout = "2006-01-02T15:04:05Z07:00"
	sessionCookieName = "session_id"
)

// SignUp is the resolver for the signUp field.
func (r *mutationResolver) SignUp(ctx context.Context, input generated.SignUpInput) (*model.User, error) {
	return r.UserUsecase.SignUp(ctx, input.Name, input.Email, input.Password)
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input generated.LoginInput) (*generated.AuthPayload, error) {
	user, sessionID, err := r.UserUsecase.Login(ctx, input.Email, input.Password)
	if err != nil {
		if errors.Is(err, usecase.ErrInvalidCredentials) {
			return nil, errors.New("メールアドレスまたはパスワードが正しくありません")
		}
		return nil, err
	}

	w := middleware.ResponseWriter(ctx)
	if w != nil {
		http.SetCookie(w, &http.Cookie{
			Name:     sessionCookieName,
			Value:    sessionID,
			HttpOnly: true,
			Path:     "/",
			Expires:  time.Now().Add(24 * time.Hour),
		})
	}

	return &generated.AuthPayload{User: user}, nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	r2 := middleware.Request(ctx)
	if r2 == nil {
		return false, nil
	}
	cookie, err := r2.Cookie(sessionCookieName)
	if err != nil {
		return false, nil
	}
	r.UserUsecase.Logout(cookie.Value)

	w := middleware.ResponseWriter(ctx)
	if w != nil {
		http.SetCookie(w, &http.Cookie{
			Name:     sessionCookieName,
			Value:    "",
			HttpOnly: true,
			Path:     "/",
			Expires:  time.Unix(0, 0),
			MaxAge:   -1,
		})
	}
	return true, nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	r2 := middleware.Request(ctx)
	if r2 == nil {
		return nil, errors.New("認証が必要です")
	}
	cookie, err := r2.Cookie(sessionCookieName)
	if err != nil {
		return nil, errors.New("認証が必要です")
	}
	return r.UserUsecase.GetUserBySessionID(ctx, cookie.Value)
}

// CreatedAt is the resolver for the createdAt field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (string, error) {
	return obj.CreatedAt.Format(timeLayout), nil
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *userResolver) UpdatedAt(ctx context.Context, obj *model.User) (string, error) {
	return obj.UpdatedAt.Format(timeLayout), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// User returns generated.UserResolver implementation.
func (r *Resolver) User() generated.UserResolver { return &userResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
